# Generated by Django 5.2.14 on 2026-05-28 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balita', '0002_balita_created_at_balita_nik_balita_no_hp_ortu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penimbangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('berat_badan', models.FloatField()),
                ('tinggi_badan', models.FloatField()),
                ('lingkar_kepala', models.FloatField(blank=True, null=True)),
                ('status_gizi', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penimbangan', to='balita.balita')),
            ],
        ),
    ]
