# Generated by Django 5.2.14 on 2026-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penimbangan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penimbangan',
            name='status_gizi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
