# Generated by Django 5.2.14 on 2026-05-29 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penimbangan', '0002_alter_penimbangan_status_gizi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penimbangan',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Penimbangan', 'verbose_name_plural': 'Data Penimbangan'},
        ),
        migrations.AddField(
            model_name='penimbangan',
            name='keterangan',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
        migrations.AddField(
            model_name='penimbangan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='penimbangan',
            name='berat_badan',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, 'Berat badan minimal 0.1 kg'), django.core.validators.MaxValueValidator(100, 'Berat badan maksimal 100 kg')], verbose_name='Berat Badan (kg)'),
        ),
        migrations.AlterField(
            model_name='penimbangan',
            name='lingkar_kepala',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20, 'Lingkar kepala minimal 20 cm'), django.core.validators.MaxValueValidator(70, 'Lingkar kepala maksimal 70 cm')], verbose_name='Lingkar Kepala (cm)'),
        ),
        migrations.AlterField(
            model_name='penimbangan',
            name='status_gizi',
            field=models.CharField(blank=True, choices=[('Gizi Buruk', 'Gizi Buruk'), ('Gizi Kurang', 'Gizi Kurang'), ('Gizi Normal', 'Gizi Normal'), ('Gizi Lebih', 'Gizi Lebih'), ('Resiko Stunting', 'Resiko Stunting')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='penimbangan',
            name='tinggi_badan',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10, 'Tinggi badan minimal 10 cm'), django.core.validators.MaxValueValidator(200, 'Tinggi badan maksimal 200 cm')], verbose_name='Tinggi Badan (cm)'),
        ),
    ]
