# Generated by Django 5.2.14 on 2026-05-29 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penimbangan', '0003_alter_penimbangan_options_penimbangan_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penimbangan',
            name='berat_badan',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, 'Berat badan minimal 0.1 kg')], verbose_name='Berat Badan (kg)'),
        ),
        migrations.AlterField(
            model_name='penimbangan',
            name='lingkar_kepala',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20, 'Lingkar kepala minimal 20 cm')], verbose_name='Lingkar Kepala (cm)'),
        ),
        migrations.AlterField(
            model_name='penimbangan',
            name='status_gizi',
            field=models.CharField(blank=True, choices=[('Gizi Buruk', 'Gizi Buruk'), ('Gizi Kurang', 'Gizi Kurang'), ('Gizi Normal', 'Gizi Normal'), ('Gizi Lebih', 'Gizi Lebih'), ('Resiko Stunting', 'Resiko Stunting')], max_length=50, null=True, verbose_name='Status Gizi'),
        ),
        migrations.AlterField(
            model_name='penimbangan',
            name='tinggi_badan',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10, 'Tinggi badan minimal 10 cm')], verbose_name='Tinggi Badan (cm)'),
        ),
    ]
