# Generated by Django 5.2.14 on 2026-05-29 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-published_at'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel Edukasi'},
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='isi',
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.CharField(choices=[('Kesehatan Balita', 'Kesehatan Balita'), ('Gizi & Nutrisi', 'Gizi & Nutrisi'), ('Imunisasi', 'Imunisasi'), ('Tumbuh Kembang', 'Tumbuh Kembang'), ('Penyakit Anak', 'Penyakit Anak'), ('Ibu & Anak', 'Ibu & Anak'), ('Lainnya', 'Lainnya')], default='Kesehatan Balita', max_length=50, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='konten',
            field=models.TextField(default='', verbose_name='Isi Artikel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='penulis',
            field=models.CharField(default='Admin SIPOS', max_length=100, verbose_name='Penulis'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Publikasi'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='ringkasan',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Ringkasan'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tags (pisahkan dengan koma)'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Jumlah Dibaca'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='artikel/', verbose_name='Gambar'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Judul Artikel'),
        ),
    ]
