# Generated by Django 5.2.14 on 2026-05-28 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balita', '0002_balita_created_at_balita_nik_balita_no_hp_ortu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imunisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('BCG', 'BCG'), ('DPT', 'DPT'), ('POLIO', 'Polio'), ('CAMPAK', 'Campak'), ('HEPATITIS', 'Hepatitis')], max_length=20)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('balita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imunisasi', to='balita.balita')),
            ],
        ),
    ]
