# Generated by Django 5.2.14 on 2026-05-29 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imunisasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imunisasi',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Imunisasi', 'verbose_name_plural': 'Data Imunisasi'},
        ),
        migrations.RemoveField(
            model_name='imunisasi',
            name='jenis',
        ),
        migrations.AddField(
            model_name='imunisasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imunisasi',
            name='jenis_imunisasi',
            field=models.CharField(choices=[('BCG', 'BCG'), ('DPT', 'DPT'), ('Polio', 'Polio'), ('Campak', 'Campak'), ('Hepatitis B', 'Hepatitis B'), ('Hib', 'Hib'), ('Rotavirus', 'Rotavirus'), ('PCV', 'PCV'), ('IPV', 'IPV'), ('JE', 'JE'), ('MMR', 'MMR'), ('Td', 'Td'), ('HPV', 'HPV'), ('Lainnya', 'Lainnya')], default=0, max_length=50, verbose_name='Jenis Imunisasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imunisasi',
            name='status',
            field=models.CharField(choices=[('Sudah', 'Sudah'), ('Belum', 'Belum'), ('Terlewat', 'Terlewat'), ('Dijadwalkan', 'Dijadwalkan')], default='Belum', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='imunisasi',
            name='tempat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tempat Pelaksanaan'),
        ),
        migrations.AddField(
            model_name='imunisasi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imunisasi',
            name='usia_saat_imunisasi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usia (bulan)'),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal Imunisasi'),
        ),
    ]
