# Generated by Django 5.2.14 on 2026-05-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imunisasi', '0002_alter_imunisasi_options_remove_imunisasi_jenis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imunisasi',
            name='jenis_imunisasi',
            field=models.CharField(choices=[('BCG', 'BCG'), ('DPT', 'DPT'), ('Polio', 'Polio'), ('Campak', 'Campak'), ('Hepatitis B', 'Hepatitis B'), ('Hib', 'Hib'), ('Rotavirus', 'Rotavirus'), ('PCV', 'PCV'), ('IPV', 'IPV'), ('JE', 'JE'), ('MMR', 'MMR'), ('Td', 'Td'), ('HPV', 'HPV'), ('Lainnya', 'Lainnya')], default='BCG', max_length=50),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='status',
            field=models.CharField(choices=[('Sudah', 'Sudah'), ('Belum', 'Belum'), ('Terlewat', 'Terlewat'), ('Dijadwalkan', 'Dijadwalkan')], default='Belum', max_length=20),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='tempat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='usia_saat_imunisasi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
