# Generated by Django 5.2.14 on 2026-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan Bulanan',
                'ordering': ['-tahun', '-bulan'],
            },
        ),
    ]
