# Generated by Django 5.2.14 on 2026-05-28 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balita',
            name='nik',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balita',
            name='no_hp_ortu',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
