# Generated by Django 5.2.14 on 2026-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balita', '0002_balita_created_at_balita_nik_balita_no_hp_ortu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balita',
            name='no_hp_ortu',
        ),
        migrations.AddField(
            model_name='balita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='balita',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
