# Generated by Django 5.2.14 on 2026-05-30 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balita', '0003_remove_balita_no_hp_ortu_balita_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balita',
            options={'ordering': ['-created_at'], 'verbose_name': 'Balita', 'verbose_name_plural': 'Data Balita'},
        ),
        migrations.AddField(
            model_name='balita',
            name='berat_lahir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Berat Lahir (kg)'),
        ),
        migrations.AddField(
            model_name='balita',
            name='catatan',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Khusus'),
        ),
        migrations.AddField(
            model_name='balita',
            name='desa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa/Kelurahan'),
        ),
        migrations.AddField(
            model_name='balita',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='balita',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ayah Kandung'),
        ),
        migrations.AddField(
            model_name='balita',
            name='no_hp_orang_tua',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='No. HP Orang Tua'),
        ),
        migrations.AddField(
            model_name='balita',
            name='rt',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='RT'),
        ),
        migrations.AddField(
            model_name='balita',
            name='rw',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='RW'),
        ),
        migrations.AddField(
            model_name='balita',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('pindah', 'Pindah'), ('keluar', 'Keluar')], default='aktif', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='balita',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir'),
        ),
        migrations.AddField(
            model_name='balita',
            name='tinggi_lahir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tinggi Lahir (cm)'),
        ),
        migrations.AddField(
            model_name='balita',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balita', to=settings.AUTH_USER_MODEL, verbose_name='Akun Orang Tua'),
        ),
        migrations.AlterField(
            model_name='balita',
            name='alamat',
            field=models.TextField(verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='balita',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='balita',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama Lengkap Balita'),
        ),
        migrations.AlterField(
            model_name='balita',
            name='nama_ibu',
            field=models.CharField(max_length=100, verbose_name='Nama Ibu Kandung'),
        ),
        migrations.AlterField(
            model_name='balita',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='balita',
            name='tanggal_lahir',
            field=models.DateField(verbose_name='Tanggal Lahir'),
        ),
    ]
