# Generated by Django 5.2.14 on 2026-05-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('lokasi', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
    ]
