# Generated by Django 5.2.14 on 2026-05-29 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwal',
            options={'ordering': ['tanggal', 'waktu_mulai'], 'verbose_name': 'Jadwal Posyandu', 'verbose_name_plural': 'Jadwal Posyandu'},
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='lokasi',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jadwal',
            name='jenis_kegiatan',
            field=models.CharField(choices=[('Penimbangan', 'Penimbangan Balita'), ('Imunisasi', 'Imunisasi'), ('Penyuluhan', 'Penyuluhan Kesehatan'), ('Kelas Ibu Hamil', 'Kelas Ibu Hamil'), ('Pemberian Vitamin', 'Pemberian Vitamin A'), ('Lainnya', 'Lainnya')], default='Penimbangan', max_length=50),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='nama_kegiatan',
            field=models.CharField(default='Kegiatan Posyandu', max_length=200),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='petugas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='status',
            field=models.CharField(choices=[('Akan Datang', 'Akan Datang'), ('Sedang Berlangsung', 'Sedang Berlangsung'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Akan Datang', max_length=20),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='tempat',
            field=models.CharField(default='Posyandu Kemuning', max_length=200),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='waktu_mulai',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='waktu_selesai',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='tanggal',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
