# Generated by Django 5.2.14 on 2026-05-30 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaderprofile',
            options={'verbose_name': 'Profil Kader', 'verbose_name_plural': 'Profil Kader'},
        ),
        migrations.AddField(
            model_name='kaderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaderprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kaderprofile',
            name='alamat',
            field=models.TextField(verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='kaderprofile',
            name='no_hp',
            field=models.CharField(max_length=15, verbose_name='No. Handphone'),
        ),
        migrations.AlterField(
            model_name='kaderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kaderprofile', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
    ]
